### ISSUE TITLE
response.xsd vs. response_new.xsd

### ISSUE THREAD

**Issue by kaiqu** [erasmus-without-paper/ewp-specs-api-mobilities#4]
Do these schemas describe different kinds of response, or are they different versions of the same thing?

**Comment by wrygiel** [comment]
They are different versions of the same thing.

We (WP4) have submitted the original (empty) `response.xsd` for WP3 to fill in. However, WP3 decided to (temporarily?) submit their own `response_new.xsd` instead of modifying ours. So, `response_new.xsd` must be merged to `response.xsd` before these specs are released.
