### ISSUE TITLE
Mobility status - live

### ISSUE THREAD

**Issue by jiripetrzelka** [erasmus-without-paper/ewp-specs-api-mobilities#45]
Is it allowed for the sending institution to present the 'live' status of its nomination even if the counterparty's imobility endpoint is not available yet or provides no data or lists the nomination status as 'pending'?
I mean, there are other ways to infer that the receiving institution has accepted the nomination, such as issuing the Letter of Acceptance or approving the LA, so if we have the information that all formalities have been settled, can we set the status to 'live'?
I would assume that the sending institution can do this because it is the owner of the data but I'm not sure how strictly should we take the workflows at https://github.com/erasmus-without-paper/ewp-specs-api-omobilities where this scenario is not described.

**Comment by kamil-olszewski-uw** [comment]
The workflows presented in the API description are examples rather than a closed list of strict procedures. Contrary to, for example, Learning Agreements, these rules are softer. The statuses on both sides are not presented to the whole world, but only to each other, and if there are any inconsistencies in them, they can simply be a signal that maybe something is wrong on business level and you need to explain it to each other.

Please also note that receiving HEI does not send information via the Incoming Mobilities API that nomination has been accepted. That is, it does not send information that the student can come, because all the formalities have been completed - and if I am not mistaken, this is the role of the Letter of Acceptance (not to mention LA approving, which is signed at a later stage). Receiving HEI may send the status "verified", which means, according to the specification: "The nomination was recognized by the receiving HEI as formally correct and complying with cooperation conditions. Now it's time for settling formalities, sending student's documents, creating the first Learning Agreement, etc."

Nevertheless, in the relatively near future, both APIs will become mandatory for universities, as is now the IIA API and LA API. A roadmap with specific dates is to be published soon. And then there will be no other ways of informing the partner that the nomination has been positively verified.

**Comment by janinamincer-daszkiewicz** [comment]
Jiri, any comments or can we close this issue?

**Comment by jiripetrzelka** [comment]
Everything is clear, thank you for the clarification.
