### ISSUE TITLE
Element naming

### ISSUE THREAD

**Issue by kaiqu** [erasmus-without-paper/ewp-specs-api-mobilities#8]
- "nominee-field-isced-code" corresponds to Subject Area Code in the model. I was under the impression that "subject area" is the general term (in this case encoded by ISCED). In that case, shouldn't the field have the more general name? Conceivably, the coding could be changed at some point, or there could be a need for more than one coding scheme - then it would make sense to use a general name and have a (possibly optional) scheme attribute? Also, why the "field" name part?
- "nominee-language-skill" corresponds to Language Competence in the model. I have seen the "competence" term used many places in the background material, and the corresponding field in Cooperation Condition is called Required Language Competence. Whatever we decide, we should at least be consistent in all entities/APIs.
- "component-studied" should in my opinion be renamed to "component-planned" - otherwise it's easy to interpret it as the component that is _actually_ studied.

**Comment by wrygiel** [comment]
> I was under the impression that "subject area" is the general term (in this case encoded by ISCED). In that case, shouldn't the field have the more general name?

This naming strategy was taken from ELMO format. In ELMO subjectArea refers to the (now deprecated) Erasmus codes (for backward-compatibility), so in EMREX we began using iscedCodes to differentiate between them. Since this element naming is used in other formats we build upon, I thought it might be good to keep it here, to avoid confusion. (Note, that EMREX ELMO is used in ToRs API.)

> then it would make sense to use a general name and have a (possibly optional) scheme attribute

Would it be possible for the reader to tell - based on the value itself - what type of subject area it is? I always thought that it is essential to clearly differentiate which type the server uses.

> Also, why the "field" name part?

This is short for "field of education". I thought it appropriate, because there are other types of ISCED codes (only one of them describes fields of education). On the other hand, EMREX ELMO ignores this issue, so perhaps we can ignore it too. Or, we could name it "isced-f" instead of just "isced", this makes it clear.

> "nominee-language-skill" corresponds to Language Competence in the model. I have seen the "competence" term used many places in the background material

@erasmus-without-paper/wp2 - what do you think? Is it better to name thing "language skill" or "language competence"? EUC has used "language skill" in their [latest IIA template](https://github.com/erasmus-without-paper/ewp-specs-api-iias/blob/a2954a97b9b7d0439df44a91cefd7bfdab114eb5/resources/template_EuropeanCommission_IIA.pdf) (section C). I just took a glance on WP2's vocabulary (`201601_Data Glossary_v2.docx`) - there's a reference to "language skills" term (although it's not defined explicitly).

> "component-studied" should in my opinion be renamed to "component-planned" - otherwise it's easy to interpret it as the component that is actually studied.

Perhaps. On the other hand, if we name it "component-planned" then it's easy to interpret it as it being only "initially planned to be studied", but not "actually studied". I tried to think of a better name, but couldn't decide which one's better. Perhaps you have some other suggestions?

BTW - because these three issues are not clearly related, it's better to report them separately to avoid clutter (one issue per element).

**Comment by kaiqu** [comment]
> This naming strategy was taken from ELMO format. In ELMO subjectArea refers to the (now deprecated) Erasmus codes (for backward-compatibility), so in EMREX we began using iscedCodes to differentiate between them. [...] I thought it might be good to keep it here, to avoid confusion. [...]
> 
> [...] I always thought that it is essential to clearly differentiate which type the server uses.

Ok, no problem.

>> Also, why the "field" name part?
> 
> This is short for "field of education". I thought it appropriate, because there are other types of ISCED codes (only one of them describes fields of education). On the other hand, EMREX ELMO ignores this issue, so perhaps we can ignore it too. Or, we could name it "isced-f" instead of just "isced", this makes it clear.

"isced-f" sounds good to me. I will change it in the model.

> @erasmus-without-paper/wp2 - what do you think? Is it better to name thing "language skill" or "language competence"? EUC has used "language skill" in their latest IIA template (section C). I just took a glance on WP2's vocabulary (201601_Data Glossary_v2.docx) - there's a reference to "language skills" term (although it's not defined explicitly).

I will align the model with whatever the group decides.

>> "component-studied" should in my opinion be renamed to "component-planned" - otherwise it's easy to interpret it as the component that is actually studied.
> 
> Perhaps. On the other hand, if we name it "component-planned" then it's easy to interpret it as it being only "initially planned to be studied", but not "actually studied". I tried to think of a better name, but couldn't decide which one's better. Perhaps you have some other suggestions?

I don't think "planned" excludes the possibility of a component being actually studied:
1. If the plan is changed, the planned component is superceded by a replacement
2. If the plan holds, the planned component is studied as well (i.e. good planning!)

Otherwise, the planned component would have to be "superceded" by an identical "studied" component in alternative 2, which doesn't make sense. Anyway, that's my opinion - maybe others will disagree...

> BTW - because these three issues are not clearly related, it's better to report them separately to avoid clutter (one issue per element).

I see your point, but since only the last issue is still under discussion from my point of view, I'm tempted to leave it as-is. But I will be more structured in the future :-)

**Comment by wrygiel** [comment]
> I don't think "planned" excludes the possibility of a component being actually studied

We need a distinction between:

* components studied, or **planned** to be studied,
* components recognized, or **planned** to be recognized.

Problem with "planned" is that it matches both of these sets because `<component-recognized>` is also not always recognized - it can be planned to be recognized. So, in this context "component planned" seems actually more vague than "component studied".

Perhaps why should change the tense in both?

**Comment by kaiqu** [comment]
> We need a distinction between:
> - components studied, or **planned** to be studied,
> - components recognized, or **planned** to be recognized.
> 
> Problem with "planned" is that it matches both of these sets because "component-recognized" is also not always recognized - it can be planned to be recognized. So, in this context "component planned" seems actually more vague than "component studied".

I see - "planned" is a boolean flag orthogonal to studied/recognized. If it's necessary to specify whether it is planned or not, there should be such a flag in the format. Otherwise, it's enough with "studied" and "recognized".

**Comment by wrygiel** [comment]
> I see your point, but since only the last issue is still under discussion from my point of view, I'm tempted to leave it as-is. But I will be more structured in the future :-)

I believe this can now be closed.

**Comment by kaiqu** [comment]
> I believe this can now be closed.

Well, there is still the matter of "language skill" vs. "language competence" - but still should of course be a separate issue...

**Comment by wrygiel** [comment]
> Well, there is still the matter of "language skill" vs. "language competence"

Ah yes, we are waiting for @erasmus-without-paper/wp2's comment on this.

**Comment by wrygiel** [comment]
> Ah yes, we are waiting for @erasmus-without-paper/wp2's comment on this.

I'm closing this due to lack of input. Also, some teams have already started development, so changing this without good reason wouldn't do much good.
